server:
  port:8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:posgresql://localhost:5432//innotech
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format.sql
    show-sql: true


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

